# Generated by Django 5.2.11 on 2026-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_approval_repairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
