# Generated by Django 5.2.11 on 2026-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_feedback_servicereminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereminder',
            name='message',
        ),
        migrations.AddField(
            model_name='servicereminder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicereminder',
            name='service_type',
            field=models.CharField(default='General Service', max_length=100),
            preserve_default=False,
        ),
    ]
